require("plugins.plugins-setup")

require("core.options")
require("core.keymaps")

require("plugins.lualine")
require("plugins.autopairs")
require("plugins.comment")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/telescope")
